### ISSUE TITLE
Could not find InAppBrowser plugin

### ISSUE THREAD

**Issue by MyBoon** [nraboy/ng-cordova-oauth#57]
I've an issue with ng-cordova-oauth that throw an error every time I want to use one of the provider (I tried with facebook and linkedin). Looking at the code, I believe this line is wrong: 

```js
if (cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser") === true)
```

Not sure why this is happening but it looks like the correct slug should be **cordova-plugin-inappbrowser** now (output given by *$> ionic plugin list*).

Let me know if I can help :)

**Comment by MyBoon** [comment]
So for some reasons I had to install the plugin by doing:

```sh
cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git
```

instead of 

```sh
cordova plugin add org.apache.cordova.inappbrowser
```

that was giving me an error (repo down?) ...
Issue can be closed since, the **cordova plugin add org.apache.cordova.inappbrowser** is working again =)

**Comment by fno** [comment]
even if i install the inappbrowser pugin the other way i still get this exact error message.

the plugin lists with 'cordova plugin list' just fine but the ng0auth returns for every provider with a "Could not find InAppBrowser plugin"

**Comment by nraboy** [comment]
Sounds like something is broken in the plugin repository.  You may want to open a ticket with Apache Cordova because both are suppose to point to the same place.

Regards,

**Comment by Takkuz** [comment]
It's not a Cordova fault:
Installing with `cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git`
Gives version **1.0.1-dev**.
Installing with `cordova plugin add org.apache.cordova.inappbrowser`
or the new `cordova plugin add cordova-plugin-inappbrowser`
Gives version **1.0.0**

ngCordova Oauth isn't able to find any of both.
Problem is on check plugin existence:
it checks for `org.apache.cordova.inappbrowser` while, right now, it's named `cordova-plugin-inappbrowser`

Changing those lines on `ngcordova.js` solves the issue.

**Comment by blvz** [comment]
+1
I've had to create a fork.

**Comment by nraboy** [comment]
I'm aware of this, but I haven't had a chance to jump in and fix it.  This is only a side project of mine.  Should have time this weekend.

**Comment by blvz** [comment]
No problem, mate. :wink:

**Comment by Takkuz** [comment]
Don't worry... Just sayin' it because I'm a beginner on GitHub. :stuck_out_tongue_winking_eye: Thanks.

**Comment by joshbuchea** [comment]
Latest version of InAppBrowser Plugin was causing issues for me also. Installing as @Takkuz suggested resolved my issues.

**Comment by nraboy** [comment]
I pushed a fix to the master.

**Comment by blvz** [comment]
Thanks a bunch, @nraboy.

**Comment by LearningTools** [comment]
Hi all I have to do to run me I still get the error console InAppBrowser Could not find plugin

**Comment by nraboy** [comment]
How are you installing the InAppBrowser plugin?

**Comment by LearningTools** [comment]
cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-inappbrowser.git

**Comment by nraboy** [comment]
Does it work if you do this instead?:

```
cordova plugin add org.apache.cordova.inappbrowser
```

Thanks,

**Comment by LearningTools** [comment]
o.k I try to be like me going

**Comment by LearningTools** [comment]
hello, now displays an error when you press the button

![captura de pantalla de 2015-05-08 10 04 51](https://cloud.githubusercontent.com/assets/4220068/7539122/52435222-f56a-11e4-8209-07c497475a32.png)

**Comment by nraboy** [comment]
I'm wondering if you're running to the problem people are reporting with the latest Apache Cordova release.  Some have reported that they are blocking remote hosts if you don't use their plugin.

Can you tell me if you get the same results when you copy the link from the simulator and paste it into your web browser?

Thanks,

**Comment by sameera207** [comment]
Had the same issue, finally @nraboy s last suggested command worked :+1: 

`cordova plugin add org.apache.cordova.inappbrowser` 

thanks heaps for all.. :smile:

**Comment by developerlaoz** [comment]
WARNING: org.apache.cordova.inappbrowser has been renamed to cordova-plugin-inappbrowser. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.inappbrowser` and `cordova plugin add cordova-plugin-inappbrowser`.

Waiting for ngCordova Update?

**Comment by developerlaoz** [comment]
It seems ng-cordova-oauth@0.1.2 already fixed it.

**Comment by manudefrutosvila** [comment]
I have installed from bower
```
"name": "ngCordova",
"version": "0.1.17-alpha",
"homepage": "http://ngCordova.com/",
```

but it seems that the source code differs form ng-cordova release of **v0.1.17-alpha**

The release is behind 10 commits of master branch and it looks like the code that checks **inappbrowser is installed** has changed since then.

in the release of 0.1.17-alpha it is still
```
if (cordovaMetadata.hasOwnProperty("org.apache.cordova.inappbrowser") === true) {
```

instead of the line that checks for the new name of the plugin and also for the old one
```
if($cordovaOauthUtility.isInAppBrowserInstalled(cordovaMetadata) === true) {
```

**Comment by nraboy** [comment]
Hey @manudefrutosvila,

I have no control over Ionic's versioning cycle since I have no affiliation with them.  I encourage you do one of three things:

1. Use ng-cordova-oauth
2. Use the master branch of ng-cordova
3. Ask Ionic to tag a new version on ng-cordova

Regards,

**Comment by rsdntevl** [comment]
So I was trying this project out after going to your blog, https://github.com/nraboy/ng-cordova-facebook-example. The ng-cordova.min.js (0.1.20-alpha) included within the project threw a "Could not find InAppBrowser plugin" error. I updated to the latest https://github.com/driftyco/ng-cordova (v0.1.23-alpha) & it is still throwing an error.

throughout the ng-cordova.js
````
var cordovaMetadata.cordova.require("cordova/plugin_list").metadata;
````
is returning an empty object, so

````
 if(cordovaMetadata.hasOwnProperty("cordova-plugin-inappbrowser") === true)
````

is returning the error message 'InAppBrowser could not find plugin'.

````
cordovaMetadata.cordova.require("cordova/plugin_list")
````
contains the plugin in an array however. Is this an ng-cordova issue then?

**Comment by EdHubbell** [comment]
@vgport is right on - I changed 

```javascript
                    var cordovaMetadata = cordova.require("cordova/plugin_list").metadata;
                    if(cordovaMetadata.hasOwnProperty("cordova-plugin-inappbrowser") === true) {
```
to 
```javascript
                    if(cordova.InAppBrowser) {
```

and I'm back up and running. The code I had was working and fine, but when I updated cordova last week it all went wonky. My cordova version is 5.4.0. 

And thanks @nraboy for the project - Very useful.

**Comment by nraboy** [comment]
This issue is being looked into.

**Comment by thiphariel** [comment]
Hi. @EdHubbell solution works here, but only on Android 6-.

On Marshmallow, browser opens but "webage not available"
https://cloud.githubusercontent.com/assets/4220068/7539122/52435222-f56a-11e4-8209-07c497475a32.png

**Comment by xunxdd** [comment]
![image](https://cloud.githubusercontent.com/assets/3663838/11188721/eb3d3168-8c51-11e5-88b7-2ae1c8b8f06d.png)

however,  var cordovaMetadata = cordova.require("cordova/plugin_list").metadata; 

cordovaMetaddata does not contains the inappbrowser, as a result, auth broke everytime.

Does anyone know why?

thanks

**Comment by nraboy** [comment]
@matheusrocha89 and I are working on a fix.  This is an issue introduced in the latest version of Apache Cordova.  Earlier versions should not be suffering from this.

Regards,

**Comment by xunxdd** [comment]
thanks a lot!!!

**Comment by cabbabu** [comment]
@nraboy a, also running thru the same issue. Could not find inappbroswer plugin in IOS..am awaiting for your response on the fix...

**Comment by matheusrocha89** [comment]
@xunxdd , @cabbabu We are testing a new version with this fix to release. You will download this version soon.

**Comment by xunxdd** [comment]
thanks a lot, really appreciated!

**Comment by jmarczew** [comment]
Just FYI, the " if(cordova.InAppBrowser)" solution works for me on Cordova 5.4.0 and Android Lollipop 5.1.1.

**Comment by nraboy** [comment]
Maybe everyone can clear something up for me because I honestly don't know the answer to this.

Must cordova.InAppBrowser be wrapped in an onDeviceReady or IonicPlatform.ready first?  My approach with the meta that worked in previous versions did not require plugins to be ready.  It just checked the meta to see if they were installed.

Requiring the plugin to be ready to check if it exists is probably not a good long term solution to this.  However, maybe cordova.InAppBrowser doesn't fall victim to this.

Thanks,

**Comment by spartan1234** [comment]
Temporary solution : using old version of cordova
npm uninstall cordova -g
npm install -g cordova@5.3.3

**Comment by mjaverto** [comment]
+1 @spartan1234 that works for me.

**Comment by yonihei** [comment]
+1 to downgrading to cordova 5.3.3
$cordovaOauth.instagram begun working again
thx :)

**Comment by vikey89** [comment]
+1 to downgrading to cordova 5.3.3

**Comment by nraboy** [comment]
This should be corrected in staging version 0.2.0 found in https://github.com/nraboy/ng-cordova-oauth/issues/167.

I encourage you to test it out.
